version: "3.5"
services:
  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: my-root-token
      VAULT_ADDR: 'http://0.0.0.0:8200'
